name: Go tests

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.23.0"
      
      - name: Check gofmt
        shell: bash
        run: |
          gofmt -l . > fmt
          if [ $(stat -c %s fmt) -gt 0 ]; then
            exit 1
          fi

      - name: Go tests
        shell: bash
        run: |
          go test
